.Dd April 22, 2014
.Dt CAT 1
.Os
.Sh NAME
.Nm cat
.Nd concat files
.Sh SYNOPSIS
.Nm
.Ar files
.Sh DESCRIPTION
The 
.Nm
utility takes a list of files, and reads them out to standard output in the order given. Effectively, this also means you can use cat as a primitive file viewer. When no parameters are given, it reads from standard input.
.Pp
Please do not use cat where it is an unnecessary part in a pipeline.
